create i18n
Yu-kichi/Fjord_Rails_Task pull request #1
Opened 2020-08-10 12:18 UTC by Yu-kichi

install i18n
install bootstrap
add not_null_book_title
create header and footer

2020-08-11 12:02 UTC, komagata requested changes

2020-08-11 12:02 UTC, komagata commented on app/helpers/books_helper.rb
> +    Book.human_attribute_name(attribute)
あまり変わってないので、新しいメソッドを導入するよりも、Rails共通の機能で、Railsを使ってる人はみんな知っているメソッドを使っている方が他の人にとってわかりやすいかもです。

2020-08-11 12:02 UTC, komagata commented on app/views/books/_flash.html.erb
> +<% end %>
最終行に改行がないようです。

2020-08-11 12:03 UTC, komagata commented
create i18nだと英語の意味的におかしいかもです。

PRのDescriptionも日本語で書くか、英語で書く場合も文章として成立するように書いた方がいいともいます。

2020-08-12 11:54 UTC, Yu-kichi commented on app/views/books/_flash.html.erb
> +<% end %>
すいません見落としてました。。
気をつけます！

2020-08-12 11:57 UTC, Yu-kichi commented on app/helpers/books_helper.rb
> +    Book.human_attribute_name(attribute)
了解です！
わかりづらいのでこのメソッドは消して、普通にhuman_attribute_nameを使うよう変更します。

2020-08-13 06:42 UTC, komagata commented
@Yu-kichi このタイトルですとスクールの課題限定の表現になっていると思います。
このプロジェクトを1つのソフトウェアプロジェクトとして考えた場合にどんな変更を目的としたPull Requestなのかをタイトルで表現する必要があります。

i18nはinternationalization（国際化）の省略形ですので、最初の「国際化を作成する」は文章としておかしくなってしまいます。

PRのDescriptionの方もその延長で、このPRがどのようなことをしたのかを説明する意味に通る文章にしてみてください。

2020-08-13 15:07 UTC, komagata requested changes
PRのTitleとDescriptionがとっても良くなったと思います。

erbの細かいところ気になるあったのでコメントさせていただきました。

[erb-lint](https://github.com/Shopify/erb-lint)などを使うとどのような書き方がいいのかわかりやすいかもしれません。

2020-08-13 15:07 UTC, komagata commented on app/views/books/index.html.erb
> +      <th colspan = "3"></th>
```suggestion
      <th colspan="3"></th>
```

2020-08-13 15:07 UTC, komagata commented on app/views/books/new.html.erb
> +  <h1><%= t'.New Book'%></h1>
```suggestion
  <h1><%= t '.New Book' %></h1>
```

2020-08-13 15:07 UTC, komagata commented on app/views/books/show.html.erb
> +  <strong><%= Book.human_attribute_name(:memo)%>:</strong>
```suggestion
  <strong><%= Book.human_attribute_name(:memo) %>:</strong>
```

2020-08-13 15:07 UTC, komagata commented on app/views/books/show.html.erb
> +  <strong><%= Book.human_attribute_name(:author)%>:</strong>
```suggestion
  <strong><%= Book.human_attribute_name(:author) %>:</strong>
```

2020-08-13 15:07 UTC, komagata commented on app/views/layouts/application.html.erb
> +    <div class= "container mb-5 ">
```suggestion
    <div class="container mb-5">
```

2020-08-13 15:07 UTC, komagata commented on app/views/layouts/application.html.erb
> +    <%= render 'fotter'%>
```suggestion
    <%= render 'fotter' %>
```

2020-08-13 15:07 UTC, komagata commented on config/locales/views/books/ja.yml
> +
最終行の改行がないマークが出ているようです〜

2020-08-16 14:24 UTC, komagata commented on app/views/books/show.html.erb
> +<%= link_to t("directory.link.Edit"), edit_book_path(@book) %> |
`directory`はどういった意味でしょうか

2020-08-16 15:06 UTC, Yu-kichi commented on app/views/books/show.html.erb
> +<%= link_to t("directory.link.Edit"), edit_book_path(@book) %> |
config/locales/defaults/ja.ymlのファイルでも下のように書いてました。。
```
ja:
  directory:
    link:
```
共通なのでdictionaryと書いたつもりでした。。
タイポといっていいか迷うレベルの違いになっていましたすいません。。
修正します😥

2020-08-19 16:26 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-08-20 11:16 UTC, merged